name: google_map_place_picker
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_maps_flutter: ^2.0.6
  geolocator: ^7.3.1
  permission_handler: ^8.1.4+1
  provider: ^6.0.0-dev
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.1.0
  tuple: ^2.0.0-nullsafety.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

